/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as CompareUser1User2RouteImport } from './routes/compare/$user1.$user2'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareUser1User2Route = CompareUser1User2RouteImport.update({
  id: '/compare/$user1/$user2',
  path: '/compare/$user1/$user2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/compare/': typeof CompareIndexRoute
  '/compare/$user1/$user2': typeof CompareUser1User2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/compare': typeof CompareIndexRoute
  '/compare/$user1/$user2': typeof CompareUser1User2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/compare/': typeof CompareIndexRoute
  '/compare/$user1/$user2': typeof CompareUser1User2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/profile/$username'
    | '/compare/'
    | '/compare/$user1/$user2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/profile/$username'
    | '/compare'
    | '/compare/$user1/$user2'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/profile/$username'
    | '/compare/'
    | '/compare/$user1/$user2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  CompareIndexRoute: typeof CompareIndexRoute
  CompareUser1User2Route: typeof CompareUser1User2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$user1/$user2': {
      id: '/compare/$user1/$user2'
      path: '/compare/$user1/$user2'
      fullPath: '/compare/$user1/$user2'
      preLoaderRoute: typeof CompareUser1User2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  CompareIndexRoute: CompareIndexRoute,
  CompareUser1User2Route: CompareUser1User2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
